name: CI/CD for ERP to AWS EC2

  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Django tests
          run: |
            python manage.py test

    build-and-deploy:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

        - name: Deploy to EC2
          env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            REPO_NAME: ${{ secrets.REPO_NAME }}
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          run: |
            ssh -i ~/.ssh/id_rsa $SSH_USER@$SSH_HOST << 'EOF'
              cd /home/ubuntu/$REPO_NAME
              git pull origin main
              export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
              docker-compose down
              docker-compose up --build -d
              docker-compose exec -T web python manage.py migrate
              docker-compose exec -T web python manage.py collectstatic --noinput
            EOF